Método para generar un conjunto de vectores ortonormal a partir de un conjunto de vectores linealmente independiente. Este es el algoritmo presentado en el ejercicio 3.26 .







In [4]:
import numpy as np 

# Definimos el conjunto de vectores (recordar que deben de ser L.I.)
# Ejemplo 1, ejemplo del libro "álgebra II de Armando Rojo"
#v1 = np.array([1,1])
#v2 = np.array([-1,2])

# Ejemplo 2, ejemplo de "Algebra Lineal de Seymour Lipscutz"
v1 = np.array([1,1,1,1])
v2 = np.array([1,2,4,5])
v3 = np.array([1,-3,-4,-2])

V = [v1,v2,v3]

U = []
n = len(V)
u1 = V[0]/np.linalg.norm(V[0])

U.append(u1)

k = 1
while k < n:
  w = V[k]- np.sum( np.dot(V[k],U[i])*U[i]  for i in range(0,k))
  w = w/np.linalg.norm(w)
  U.append(w)
  k = k+1

# Imprimimos los vectores de la nueva base ortonormal
for i in U:
    print(i)


[0.5 0.5 0.5 0.5]
[-0.63245553 -0.31622777  0.31622777  0.63245553]
[ 0.53039484 -0.56354451 -0.4309458   0.46409548]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
